language: node_js
node_js:
  - '10'
  - '8'
  - '7'
addons:
  apt:
    packages:
      - xvfb
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
  - npm install
  - npm install electron@2
script:
  - npm run lint
  - npm run test:main
  - npm run test:renderer
