

defaults: &defaults
  working_directory: ~/avaron
  docker:
    - image: bokuweb/node-xcb-xvfb
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install libdbus-1-3-1.12.2
            yarn install
      - run:
          name: Test
          command: |
            xvfbd start
            yarn run test:main
            yarn run test:renderer
            xvfbd stop    

