

defaults: &defaults
  working_directory: ~/avaron
  docker:
    - image: bokuweb/docker-node-browser
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm i -g yarn
            yarn install
      - run:
          name: Test
          command: |
            xvfbd start
            yarn run test:main
            yarn run test:renderer
            xvfbd stop    

